asset_path: /home/pascal/Downloads/NewMagnetPosition/Magnet.stl
usd_dir: /home/pascal/Downloads/NewMagnetPosition/Magnet
usd_file_name: Magnet.usd
force_usd_conversion: true
make_instanceable: true
mass_props:
  mass: 0.00048
  density: null
rigid_props:
  rigid_body_enabled: null
  kinematic_enabled: null
  disable_gravity: null
  linear_damping: null
  angular_damping: null
  max_linear_velocity: null
  max_angular_velocity: null
  max_depenetration_velocity: null
  max_contact_impulse: null
  enable_gyroscopic_forces: null
  retain_accelerations: null
  solver_position_iteration_count: null
  solver_velocity_iteration_count: null
  sleep_threshold: null
  stabilization_threshold: null
collision_props:
  collision_enabled: null
  contact_offset: null
  rest_offset: null
  torsional_patch_radius: null
  min_torsional_patch_radius: null
collision_approximation: convexDecomposition
translation: !!python/tuple
- -0.001713
- 0.0
- 0.0
rotation: !!python/tuple
- 1.0
- 0.0
- 0.0
- 0.0
scale: !!python/tuple
- 0.001
- 0.001
- 0.001
##
# Generated by MeshConverter on 2025-07-01 at 13:58:48.
##
